export const initialState = {
  currentDate: new Date().toISOString(),
  viewMode: "weekly",
  events: {
    byId: {
      event1: {
        id: "event1",
        title: "프로젝트 회의",
        description: "캘린더 앱 개발 진행 상황 공유 및 향후 계획 논의",
        date: "2024-06-26",
        startedAt: "14",
        endedAt: "15",
      },
      event2: {
        id: "event2",
        title: "개발 회의",
        description: "개발바닥",
        date: "2024-06-27",
        startedAt: "16",
        endedAt: "17",
      },
      event3: {
        id: "event3",
        title: "바닐라코딩 회의",
        description: "17기 취업",
        date: "2024-06-27",
        startedAt: "04",
        endedAt: "05",
      },
      event4: {
        id: "event4",
        title: "레체와 산책",
        description: "잔디 밭에서 공놀이하기",
        date: "2024-06-29",
        startedAt: "12",
        endedAt: "13",
      },
      event5: {
        id: "event5",
        title: "Redux 씹어먹기",
        description: "이빨 나가기 전까지 씹어먹기",
        date: "2024-06-29",
        startedAt: "11",
        endedAt: "12",
      },
      event6: {
        id: "event6",
        title: "JavaScript 스터디",
        description: "참조의 모든 것",
        date: "2024-06-30",
        startedAt: "14",
        endedAt: "15",
      },
    },
    allIds: ["event1", "event2", "event3", "event4", "event5", "event6"],
  },
  dates: {
    byId: {
      "2024-06-26": {
        id: "date1",
        startedAt: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "event1",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      "2024-06-27": {
        id: "date2",
        startedAt: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "event2",
          "event3",
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      "2024-06-29": {
        id: "date3",
        startedAt: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "event5",
          "event4",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      "2024-06-30": {
        id: "date4",
        events: ["event6"],
        startedAt: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "event6",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
    },
    allIds: ["date1", "date2", "date3", "date4"],
  },
};

export default initialState;
